# Generated by Django 5.1.3 on 2024-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink_org_chart_app', '0005_sharedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='INK-ID', max_length=20, unique=True),
        ),
    ]
