# Generated by Django 5.1.3 on 2024-12-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink_org_chart_app', '0007_remove_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(related_name='projects', to='ink_org_chart_app.employee')),
            ],
        ),
    ]
